package:
  name: T_reX_LCA
  version: 0.2.2

source:
  url: https://github.com/Stew-McD/T-reX/archive/0.2.2.tar.gz
  sha256: 1234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef

build:
  number: 0
  noarch: python
  script: python -m pip install . --no-deps --ignore-installed

requirements:
  build:
    - python
    - setuptools
    - wheel
  run:
    - python >=3.10,<3.12
    - brightway2 ==2.4.6
    - premise ==2.0.2
    - cowsay ==6.1

test:
  imports:
    - T_reX

about:
  home: https://github.com/Stew-McD/T-reX
  license: CC0 1.0 Universal (CC0 1.0) Public Domain Dedication
  license_family: CC0
  license_file: LICENSE
  summary: A tool for analysing waste and material footprints in Life Cycle Assessment (LCA) databases
  description: |
    T_reX_LCA is a tool for analysing waste and material footprints in Life Cycle Assessment (LCA) databases.
    It provides functionality for [describe features briefly].
  doc_url: https://T-reX.readthedocs.io/en/latest/
  dev_url: https://github.com/Stew-McD/T-reX
  recipe-maintainers:
    - Stew-McD (Stewart Charles McDowall)
