version: 2

sphinx:
  configuration: docs/source/conf.py

formats: all
# Set the version of Python
build:
  os: ubuntu-20.04 
  tools:
    python: "3.11"


python:
  install:
    - method: pip
      path: .
    - requirements: docs/requirements.txt