version: 2

sphinx:
  configuration: docs/source/conf.py
  fail_on_warning: true
  fail_on_error: true

formats: all

build:
  os: ubuntu-22.04
  tools:
    python: "3"
  apt_packages:
    - tree

python:
  install:
    - requirements: requirements.txt